# Generated by Django 4.1.3 on 2022-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amnt',
            field=models.IntegerField(),
        ),
    ]
