# Generated by Django 4.1.3 on 2022-12-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amnt',
            field=models.IntegerField(default=0),
        ),
    ]
