# Generated by Django 4.1.3 on 2023-01-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_category_alter_auction_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categoryName',
        ),
    ]
